version: '3.9'

services:
  node:
    build: .
    command: npm start
    restart: unless-stopped
    env_file:
     - .env
    ports:
     - 80:80
    volumes:
      - ./data:/usr/app/
      - /usr/app/node_modules
